import { type NextPage } from "next";
import Head from "next/head";

import { ThreeD } from "../components/threed";
import { Player } from "../components/player";
import { About } from "../components/about";
import { Contributions } from "../components/contributions";
import { Pictures } from "../components/pictures";
import { Mailer } from "../components/mailer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Cauã Adomaitis | Fullstack Developer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-screen flex-col items-center justify-center gap-[22px] bg-[rgb(3,3,1)] md:flex-row md:items-start">
        <div className="mt-32 flex  h-full flex-col gap-[22px] md:mb-32">
          <About />
          <Player />
          <ThreeD
            splineUrl={
              "https://prod.spline.design/X3Ccee1d1BhNTpnu/scene.splinecode"
            }
          />
        </div>
        <div className="mb-32 flex h-full flex-col gap-[22px] md:mt-32">
          <Contributions />
          <Pictures />
          <Mailer />
        </div>
      </main>
    </>
  );
};

export default Home;
