import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import profilePic from "../../public/images/IMG_1294.png";
import githubContributions from "../../public/images/contributions.svg";
import warhaus from "../../public/images/warhaus.svg";
import noronha from "../../public/images/IMG_4382.png";
import send from "../../public/images/send.svg";

import Spline from "@splinetool/react-spline";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen items-center justify-center gap-[22px] bg-[#010B00]">
        <div className="flex h-[80%] flex-col gap-[22px]">
          <div className="flex w-[366px] flex-col gap-4 rounded-2xl border border-white/10 bg-black p-6 text-white">
            <Image
              src={profilePic}
              alt="me"
              className="h-[93px] w-[93px] rounded-full object-cover shadow-lg shadow-white/10"
            />
            <h1 className="text-2xl font-medium">Cauã Adomaitis</h1>
            <p className="text-sm text-white/60">
              Fullstack developer from São Paulo, based in Boston.
            </p>
            <p className="text-sm text-white/60">
              I am currently developing{" "}
              <span className="text-white">qualidadeinteligente</span>, and
              studying Computer Science.
            </p>
          </div>
          <div className="flex w-[366px] items-center gap-2 rounded-2xl border border-white/10 bg-black p-2 text-white">
            <Image src={warhaus as string} alt="album of the week" />
            <p className="text-sm font-medium">{`Warhaus - Love's a Stranger`}</p>
          </div>
          <div className="flex w-[366px] flex-col rounded-2xl border border-white/10 bg-black p-6 text-white">
            <Spline
              height={256}
              scene="https://prod.spline.design/X3Ccee1d1BhNTpnu/scene.splinecode"
            />
            <p className="text-sm font-medium">qualidadeinteligente</p>
          </div>
        </div>
        <div className="flex h-[80%] flex-col gap-[22px]">
          <Link
            href="https://github.com/adomaitisc"
            target="_blank"
            className="group flex w-[366px] cursor-pointer flex-col rounded-2xl border border-white/10 bg-black p-6 text-white"
          >
            <Image
              src={githubContributions as string}
              alt="contributions"
              className="duration-300 group-hover:scale-110"
            />
            <p className="text-sm font-medium">github/adomaitisc</p>
          </Link>
          <div className="group relative flex w-[366px] flex-col overflow-hidden rounded-2xl border border-white/10 bg-black text-white">
            <Image
              src={noronha}
              alt="contributions"
              className="object-fit rounded-2xl duration-300 group-hover:scale-110"
            />
            <p className="absolute left-6 bottom-6 text-sm font-medium">
              Fernando de Noronha
            </p>
          </div>
          <div className="flex w-[366px] flex-col gap-[12px] rounded-2xl border border-white/10 bg-black p-3 text-white">
            <textarea
              className="h-[96px] w-full rounded-lg bg-zinc-900 p-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-white/40"
              placeholder="Send me a message"
            />
            <div className="relative w-full">
              <input
                placeholder="Your email"
                className="w-full rounded-lg bg-zinc-900 p-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-white/40"
              />
              <button className="absolute right-6 my-auto h-full">
                <Image src={send as string} alt="send message" />
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
